version = 1

test_patterns = [
    "tests/**",
    "test_*.py"
]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"
  max_line_length = 120
  skip_doc_coverage = ["module", "magic", "init", "class", "nonpublic"]
  type_checker = "mypy"
  additional_builtins = ["_", "pretty_output"]
